### ISSUE TITLE
Maybe transpile to ES5?

### ISSUE THREAD

**Issue by kisenka** [reshape/reshape#12]
Pleeeease

**Comment by jescalan** [comment]
why?

**Comment by kisenka** [comment]
Because some CI/Docker images/etc use old nodejs runtimes.
I mean add transpiled code in distribution under es5 folder or something.

**Comment by jescalan** [comment]
Which CIs do not support node 6? And is there any reason you can't just use [nvm](https://github.com/creationix/nvm) to manage versions on your docker image? You can just drop a `.nvmrc` file in your project root with `6` as the contents and you should be set.'

What is the context that you're trying to use reshape in? Are you starting a new project and considering it, or trying to replace another tool in an older project?

**Comment by kisenka** [comment]
@jescalan so answer is "no"? :)

**Comment by jescalan** [comment]
I haven't given an answer. I'm trying to understand why you need ES5, so I can determine whether this is a common need or specific to a very small number of use cases.

Transpiling everything adds a huge amount of extra code weight and effort to each release. Also the clock is ticking on node 4 going to end-of-life. Because of this, I don't want to do it unless it's really important or common, or there is really no way around it. It's much better if you could, for example, just use nvm rather than adding a boatload of extra code and process to releases to reshape and every single one of the plugins for it.

**Comment by kisenka** [comment]
I have a nodejs project with strict 4.\* version limitation. This project is not ready to upgrade 6.\* only because of some dependencies can't work on current setup. On the other hand - if it will be transpiled code I will force nodejs version upgrading.

**Comment by jescalan** [comment]
Could you tell me a little more about this project and how you're trying to implement reshape in it?

**Comment by kisenka** [comment]
I totally migrate to node 6 :)
