### ISSUE TITLE
Reshape vs PostHTML?

### ISSUE THREAD

**Issue by allmarkedup** [reshape/reshape#50]
Hi - I'm looking for a HTML parser/modifier/generator to use in an open source project that I maintain. Reshape looks great and I'm pretty excited that I stumbled across it. However I'm wondering what the key differences are between it and PostHTML. I notice that @jescalan is a (primary?) contributor to both these projects and on the face of it they seem very similar.

As far as I can tell the main difference is that Reshape provides a clearer separation between the parsing and code generation steps. Is there anything else that I should be aware of? I certainly like that feature but I'm trying to weigh up the benefits of that vs. the benefits of using a project that seemingly has a larger and more mature community of plugins behind it.

Any pointers that could help me make my decision easier would be much appreciated, and thanks for the great work putting this together :-)

**Comment by jescalan** [comment]
Hi @allmarkedup -- I started my journey contributing to posthtml, but ended up having to fork it because of differences in development pace and ideas between myself and the existing contributors. Since I had rewritten all of the code from the ground up by that point, I figured it should just be spun into its own project.

The main difference is that reshape's primary output is a javascript function, whereas posthtml's is a string. This means that reshape can generate templates which can be executed on the client side if necessary, or static markup (by just calling the function), where this isn't possible for posthtml, and would not be possible without a full rewrite and massively breaking changes to every plugin in the ecosystem. Something that also bothered me when working on posthtml was the lack of a clean and consistent code style, and a lack of tests and test coverage. As such, reshape has 100% test coverage on just about all of its projects, and the code style is enforced by standard.js (although this will likely move to the almost exactly the same, but easier to format prettier over the next couple months).

Reshape is *very* actively maintained and used in production for a number of large projects. We have also been pushing boundaries with plugins like [preact-components](https://github.com/reshape/preact-components). I'm not sure if you could say the same for posthtml, which seems to have pretty much stagnated over the last couple months. I think when it comes down to it, the major distinction is quality. There are more plugins for posthtml, but many of them are bugged, unmaintained, and untested. I am taking extra careful steps to make sure that this does not happen with reshape, and that plugins are solid, well-tested, and reliable, since it's an essential project for my company, the many other companies we have built projects for on top of it, and just about all my day-to-day work.

I hope this answers the question, and you are very welcome to come join us in either the [reshape gitter chat](https://gitter.im/reshape/reshape), or the more active and community oriented [static-dev slack](https://static-dev-slack.herokuapp.com/), which has a dedicated room for reshape, if you'd like to chat more!

**Comment by jescalan** [comment]
Also, just want to mention that I am a big fan of what you guys do over at Clearleft 👬

**Comment by allmarkedup** [comment]
@jescalan thanks for the comprehensive reply Jeff! Much appreciated, and your focus on quality certainly makes Reshape an attractive choice for what I'm looking for. I've also been playing around a little with writing plugins and at first glance it seems much more straightforward to do in Reshape (using the plugin utils you provide) which is a big win for me. I'm going to carry on with a few little experiments but it's feeling very nice so far.

And thanks for the links - I'm slowly drowning in Slack channels right now but if I need any advice going forwards I'll be sure to drop in.

Keep up the great work and all the best :-)

**Comment by jescalan** [comment]
Hah, totally understood with the slack channels. Best of luck, and always here to help if you have any questions or thoughts!
