### ISSUE TITLE
Reshape Markup Support

### ISSUE THREAD

**Issue by orenmizr** [reshape/reshape#52]
i read about the reasoning behind reshape. i think i get it. but when trying to write what i recognize as pug style syntax, there was no support in my editor. 

most have support and eco-system around pug/jade - couldn't it be utilized ?

**Comment by jescalan** [comment]
So this is an issue for sugarml I assume, since thats the syntax similar to jade/pug, but will answer here either way. Yes - we have an atom syntax package and have for quite a while, you can [find it here](https://github.com/reshape/atom-sugarml), and it was forked from the jade package. I am more than happy to accept and publicize other editor syntaxes if anyone will contribute - remember this is open source 😁
