### ISSUE TITLE
[bug]: incorrectly parsee without closing tag

### ISSUE THREAD

**Issue by Scrum** [reshape/reshape#60]
Does not throw errors and does not return result

```js
var reshape = require('reshape');

let html = `<div>test<span>test</div>`;

reshape()
	.process(html)
	.then((result) => {
            console.log(result.output())
	})
```

**Comment by jescalan** [comment]
Yeah, invalid html will trip up reshape pretty badly. I won't have time to handle this for a little bit - interested in submitting a PR for this at all?

**Comment by Scrum** [comment]
Not very much interested, but you can give me access (git, npm) and I'll fix this bug in my free time and maybe others...

**Comment by jescalan** [comment]
I think you should be able to accomplish this by forking the repo without needing direct access, no?

**Comment by Scrum** [comment]
you do not have time to deal with this project and I do not want to constantly wait when you have time to publish or take a pull request

**Comment by jescalan** [comment]
Ivan, I'm not sure if this is a language barrier type of thing, but I read this comment as extremely rude and abrasive. I'll assume this was not your intent, but please try to be thoughtful in the way that you word things if you can.

To reply to the claim here, I'm not sure what has caused you to conclude this. I have responded to your comments on this issue, and any other issue or pull request you have opened in as timely a manner as possible. In this case, it has been within a couple hours for most comments, a day or so for the other, as I was traveling and didn't have access to the internet.

I'd encourage you, rather than making assumptions about how much time I have available, to give it a try. If you find that you have submitted a few pull requests that haven't been merged for a long time, or that merged pull requests are being published too slowly for your tastes, let's talk about it again when that happens. There is a big difference between not having time to implement a feature and not having time to review a pull request.

**Comment by Scrum** [comment]
> I'd encourage you, rather than making assumptions about how much time I have available, to give it a try.

> I won't have time to handle this for a little bit

I made them on the basis of the fact that I once gave you one of my projects of the `reshape-cli` to which you took and did not give me more access to him on the githaba. I have the right to say so on the basis of the repository you made with respect to the `reshape-cli`.

I propose to close this discussion, I no longer are interested in your project as an offer to support your project. 

All the best.

**Comment by jescalan** [comment]
> I made them on the basis of the fact that I once gave you one of my projects of the reshape-cli to which you took and did not give me more access to him on the githaba.

1. You asked that the project be moved into the core, I did not "take" it. I was happy to do so, since you requested it, and I greatly appreciated your contribution. If you'd like for it to be moved back out, you are more than welcome to do so, it's entirely your project, as it has always been.

2. I just checked the repo, and you do have full access to it. If you are having issues accessing it, it might be an issue with github, and worth reaching out to their support to ask about. If there's anything else I can do to help ensure you have access, let me know and I will do my best to make sure it happens.

> I propose to close this discussion, I no longer are interested in your project as an offer to support your project.

Ok! Thank you for your initial offer. I will make sure this issue is closed out as soon as I have time to do so. In the meantime, for anyone else looking into this issue, make sure that you are passing valid html through reshape and it will work perfectly well, as it has been in production for many projects for years.
